/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphIdRouteImport } from './routes/graph.$id'
import { Route as DocIdRouteImport } from './routes/doc.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIdRoute = GraphIdRouteImport.update({
  id: '/graph/$id',
  path: '/graph/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repo': typeof RepoRoute
  '/search': typeof SearchRoute
  '/doc/$id': typeof DocIdRoute
  '/graph/$id': typeof GraphIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repo': typeof RepoRoute
  '/search': typeof SearchRoute
  '/doc/$id': typeof DocIdRoute
  '/graph/$id': typeof GraphIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repo': typeof RepoRoute
  '/search': typeof SearchRoute
  '/doc/$id': typeof DocIdRoute
  '/graph/$id': typeof GraphIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repo' | '/search' | '/doc/$id' | '/graph/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repo' | '/search' | '/doc/$id' | '/graph/$id'
  id: '__root__' | '/' | '/repo' | '/search' | '/doc/$id' | '/graph/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoRoute: typeof RepoRoute
  SearchRoute: typeof SearchRoute
  DocIdRoute: typeof DocIdRoute
  GraphIdRoute: typeof GraphIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/$id': {
      id: '/graph/$id'
      path: '/graph/$id'
      fullPath: '/graph/$id'
      preLoaderRoute: typeof GraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoRoute: RepoRoute,
  SearchRoute: SearchRoute,
  DocIdRoute: DocIdRoute,
  GraphIdRoute: GraphIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
