/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as GraphIdRouteImport } from './routes/graph.$id'
import { Route as DocIdRouteImport } from './routes/doc.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIdRoute = GraphIdRouteImport.update({
  id: '/graph/$id',
  path: '/graph/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plugins': typeof PluginsRoute
  '/repo': typeof RepoRoute
  '/search': typeof SearchRoute
  '/doc/$id': typeof DocIdRoute
  '/graph/$id': typeof GraphIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plugins': typeof PluginsRoute
  '/repo': typeof RepoRoute
  '/search': typeof SearchRoute
  '/doc/$id': typeof DocIdRoute
  '/graph/$id': typeof GraphIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plugins': typeof PluginsRoute
  '/repo': typeof RepoRoute
  '/search': typeof SearchRoute
  '/doc/$id': typeof DocIdRoute
  '/graph/$id': typeof GraphIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plugins'
    | '/repo'
    | '/search'
    | '/doc/$id'
    | '/graph/$id'
    | '/settings/providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plugins'
    | '/repo'
    | '/search'
    | '/doc/$id'
    | '/graph/$id'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/plugins'
    | '/repo'
    | '/search'
    | '/doc/$id'
    | '/graph/$id'
    | '/settings/providers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PluginsRoute: typeof PluginsRoute
  RepoRoute: typeof RepoRoute
  SearchRoute: typeof SearchRoute
  DocIdRoute: typeof DocIdRoute
  GraphIdRoute: typeof GraphIdRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/$id': {
      id: '/graph/$id'
      path: '/graph/$id'
      fullPath: '/graph/$id'
      preLoaderRoute: typeof GraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PluginsRoute: PluginsRoute,
  RepoRoute: RepoRoute,
  SearchRoute: SearchRoute,
  DocIdRoute: DocIdRoute,
  GraphIdRoute: GraphIdRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
